# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('level', models.CharField(max_length=10, verbose_name='level name')),
                ('module', models.CharField(blank=True, max_length=50, null=True, verbose_name='module')),
                ('process', models.IntegerField(blank=True, null=True, verbose_name='module')),
                ('thread', models.IntegerField(blank=True, null=True, verbose_name='thread')),
                ('text', models.TextField(verbose_name='text')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html')),
            ],
        ),
        migrations.CreateModel(
            name='LoggingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True, verbose_name='chat id')),
                ('type', models.CharField(choices=[('TELEGRAM', 'Telegram')], max_length=20, verbose_name='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loggingmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlogging.LoggingUser'),
        ),
    ]
